[colors]
background = '#002d38'
foreground = '#98a7a8'
selection-background = '#0d3844'
selection-foreground = '#20b2a4'
cursor = '#98a7a8'
black = '#0d3844'
red = '#ef4c47'
green = '#60a319'
yellow = '#b08800'
blue = '#3f8eef'
magenta = '#d55aa4'
cyan = '#00a497'
white = '#98a7a8'
light_black = '#677575'
light_red = '#ff5b54'
light_green = '#6eb12e'
light_yellow = '#be9600'
light_blue = '#4d9cff'
light_magenta = '#e468b1'
light_cyan = '#20b2a4'
light_white = '#b4c3c4'
