[colors]
background = '#fef6df'
foreground = '#707d82'
selection-background = '#f1e9d2'
selection-foreground = '#00988b'
cursor = '#707d82'
black = '#f1e9d2'
red = '#e13e3b'
green = '#559600'
yellow = '#a27d00'
blue = '#3282e2'
magenta = '#c74e97'
cyan = '#00988b'
white = '#707d82'
light_black = '#9caaaf'
light_red = '#e13e3b'
light_green = '#559600'
light_yellow = '#a27d00'
light_blue = '#3282e2'
light_magenta = '#c74e97'
light_cyan = '#00988b'
light_white = '#5a676b'
