" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Helium Dark
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Helium-Dark"

" Normal colors
hi Normal guifg=#98a7a8 guibg=#002d38

" Syntax highlighting groups
hi Comment guifg=#677575
hi Constant guifg=#b08800
hi Identifier guifg=#3f8eef
hi Statement guifg=#ff5b54
hi PreProc guifg=#e468b1
hi Type guifg=#6eb12e
hi Special guifg=#20b2a4
hi Underlined guifg=#4d9cff gui=underline
hi Error guifg=#ef4c47 guibg=#002d38
hi Todo guifg=#be9600 guibg=#002d38

" Additional groups for better compatibility
hi String guifg=#60a319
hi Character guifg=#60a319
hi Number guifg=#b08800
hi Boolean guifg=#b08800
hi Float guifg=#b08800

hi Function guifg=#3f8eef

hi Conditional guifg=#ff5b54
hi Repeat guifg=#ff5b54
hi Label guifg=#ff5b54
hi Operator guifg=#98a7a8
hi Keyword guifg=#ff5b54
hi Exception guifg=#ef4c47

hi Include guifg=#e468b1
hi Define guifg=#e468b1
hi Macro guifg=#e468b1
hi PreCondit guifg=#e468b1

hi StorageClass guifg=#6eb12e
hi Structure guifg=#6eb12e
hi Typedef guifg=#6eb12e

hi SpecialChar guifg=#20b2a4
hi Tag guifg=#20b2a4
hi Delimiter guifg=#98a7a8
hi SpecialComment guifg=#677575
hi Debug guifg=#be9600

hi Ignore guifg=#002d38

" Cursor and line highlighting
hi Cursor guifg=#002d38 guibg=#98a7a8
hi CursorLine guibg=#0d3844
hi CursorColumn guibg=#0d3844

" Visual selection
hi Visual guibg=#0d3844

" Search highlighting
hi Search guibg=#be9600 guifg=#002d38
hi IncSearch guibg=#be9600 guifg=#002d38

" Line numbers
hi LineNr guifg=#677575
hi CursorLineNr guifg=#98a7a8

" Status line
hi StatusLine guifg=#98a7a8 guibg=#677575
hi StatusLineNC guifg=#677575 guibg=#002d38

" Tab line
hi TabLine guifg=#677575 guibg=#002d38
hi TabLineSel guifg=#98a7a8 guibg=#0d3844
hi TabLineFill guibg=#002d38

" Popup menu
hi Pmenu guifg=#98a7a8 guibg=#677575
hi PmenuSel guifg=#002d38 guibg=#0d3844
hi PmenuSbar guibg=#677575
hi PmenuThumb guibg=#98a7a8

" Diff highlighting
hi DiffAdd guibg=#60a319
hi DiffChange guibg=#b08800
hi DiffDelete guibg=#ef4c47
hi DiffText guibg=#3f8eef

" Fold highlighting
hi Folded guifg=#677575 guibg=#002d38
hi FoldColumn guifg=#677575 guibg=#002d38

" Spell checking
hi SpellBad gui=undercurl guisp=#ef4c47
hi SpellCap gui=undercurl guisp=#3f8eef
hi SpellRare gui=undercurl guisp=#d55aa4
hi SpellLocal gui=undercurl guisp=#00a497

" Error and warning messages
hi ErrorMsg guifg=#ef4c47
hi WarningMsg guifg=#b08800
hi MoreMsg guifg=#3f8eef
hi Question guifg=#60a319

" Mode message
hi ModeMsg guifg=#60a319

" Directory
hi Directory guifg=#3f8eef

" Title
hi Title guifg=#d55aa4

" Match parenthesis
hi MatchParen guibg=#677575

" Sign column
hi SignColumn guifg=#677575 guibg=#002d38
