" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Helium Light
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Helium-Light"

" Normal colors
hi Normal guifg=#707d82 guibg=#fef6df

" Syntax highlighting groups
hi Comment guifg=#9caaaf
hi Constant guifg=#a27d00
hi Identifier guifg=#3282e2
hi Statement guifg=#e13e3b
hi PreProc guifg=#c74e97
hi Type guifg=#559600
hi Special guifg=#00988b
hi Underlined guifg=#3282e2 gui=underline
hi Error guifg=#e13e3b guibg=#fef6df
hi Todo guifg=#a27d00 guibg=#fef6df

" Additional groups for better compatibility
hi String guifg=#559600
hi Character guifg=#559600
hi Number guifg=#a27d00
hi Boolean guifg=#a27d00
hi Float guifg=#a27d00

hi Function guifg=#3282e2

hi Conditional guifg=#e13e3b
hi Repeat guifg=#e13e3b
hi Label guifg=#e13e3b
hi Operator guifg=#707d82
hi Keyword guifg=#e13e3b
hi Exception guifg=#e13e3b

hi Include guifg=#c74e97
hi Define guifg=#c74e97
hi Macro guifg=#c74e97
hi PreCondit guifg=#c74e97

hi StorageClass guifg=#559600
hi Structure guifg=#559600
hi Typedef guifg=#559600

hi SpecialChar guifg=#00988b
hi Tag guifg=#00988b
hi Delimiter guifg=#707d82
hi SpecialComment guifg=#9caaaf
hi Debug guifg=#a27d00

hi Ignore guifg=#fef6df

" Cursor and line highlighting
hi Cursor guifg=#fef6df guibg=#707d82
hi CursorLine guibg=#f1e9d2
hi CursorColumn guibg=#f1e9d2

" Visual selection
hi Visual guibg=#f1e9d2

" Search highlighting
hi Search guibg=#a27d00 guifg=#fef6df
hi IncSearch guibg=#a27d00 guifg=#fef6df

" Line numbers
hi LineNr guifg=#9caaaf
hi CursorLineNr guifg=#707d82

" Status line
hi StatusLine guifg=#707d82 guibg=#9caaaf
hi StatusLineNC guifg=#9caaaf guibg=#fef6df

" Tab line
hi TabLine guifg=#9caaaf guibg=#fef6df
hi TabLineSel guifg=#707d82 guibg=#f1e9d2
hi TabLineFill guibg=#fef6df

" Popup menu
hi Pmenu guifg=#707d82 guibg=#9caaaf
hi PmenuSel guifg=#fef6df guibg=#f1e9d2
hi PmenuSbar guibg=#9caaaf
hi PmenuThumb guibg=#707d82

" Diff highlighting
hi DiffAdd guibg=#559600
hi DiffChange guibg=#a27d00
hi DiffDelete guibg=#e13e3b
hi DiffText guibg=#3282e2

" Fold highlighting
hi Folded guifg=#9caaaf guibg=#fef6df
hi FoldColumn guifg=#9caaaf guibg=#fef6df

" Spell checking
hi SpellBad gui=undercurl guisp=#e13e3b
hi SpellCap gui=undercurl guisp=#3282e2
hi SpellRare gui=undercurl guisp=#c74e97
hi SpellLocal gui=undercurl guisp=#00988b

" Error and warning messages
hi ErrorMsg guifg=#e13e3b
hi WarningMsg guifg=#a27d00
hi MoreMsg guifg=#3282e2
hi Question guifg=#559600

" Mode message
hi ModeMsg guifg=#559600

" Directory
hi Directory guifg=#3282e2

" Title
hi Title guifg=#c74e97

" Match parenthesis
hi MatchParen guibg=#9caaaf

" Sign column
hi SignColumn guifg=#9caaaf guibg=#fef6df
