# Helium Dark
kern.vt.color.0.rgb="#0d3844"
kern.vt.color.1.rgb="#ef4c47"
kern.vt.color.2.rgb="#60a319"
kern.vt.color.3.rgb="#b08800"
kern.vt.color.4.rgb="#3f8eef"
kern.vt.color.5.rgb="#d55aa4"
kern.vt.color.6.rgb="#00a497"
kern.vt.color.7.rgb="#98a7a8"
kern.vt.color.8.rgb="#677575"
kern.vt.color.9.rgb="#ff5b54"
kern.vt.color.10.rgb="#6eb12e"
kern.vt.color.11.rgb="#be9600"
kern.vt.color.12.rgb="#4d9cff"
kern.vt.color.13.rgb="#e468b1"
kern.vt.color.14.rgb="#20b2a4"
kern.vt.color.15.rgb="#b4c3c4"
