;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(254,246,223,1)
fgcolor=rgb(112,125,130)
palette_color_0=rgb(241,233,210)
palette_color_1=rgb(225,62,59)
palette_color_10=rgb(85,150,0)
palette_color_11=rgb(162,125,0)
palette_color_12=rgb(50,130,226)
palette_color_13=rgb(199,78,151)
palette_color_14=rgb(0,152,139)
palette_color_15=rgb(90,103,107)
palette_color_2=rgb(85,150,0)
palette_color_3=rgb(162,125,0)
palette_color_4=rgb(50,130,226)
palette_color_5=rgb(199,78,151)
palette_color_6=rgb(0,152,139)
palette_color_7=rgb(112,125,130)
palette_color_8=rgb(156,170,175)
palette_color_9=rgb(225,62,59)
color_preset=Helium Light
