;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(0,45,56,1)
fgcolor=rgb(152,167,168)
palette_color_0=rgb(13,56,68)
palette_color_1=rgb(239,76,71)
palette_color_10=rgb(110,177,46)
palette_color_11=rgb(190,150,0)
palette_color_12=rgb(77,156,255)
palette_color_13=rgb(228,104,177)
palette_color_14=rgb(32,178,164)
palette_color_15=rgb(180,195,196)
palette_color_2=rgb(96,163,25)
palette_color_3=rgb(176,136,0)
palette_color_4=rgb(63,142,239)
palette_color_5=rgb(213,90,164)
palette_color_6=rgb(0,164,151)
palette_color_7=rgb(152,167,168)
palette_color_8=rgb(103,117,117)
palette_color_9=rgb(255,91,84)
color_preset=Helium Dark
